# Generated by Django 4.2.6 on 2023-10-16 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Furniture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('description', models.TextField()),
                ('color', models.CharField(max_length=50)),
                ('tags', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('Lighting', 'Lighting'), ('Furniture', 'Furniture'), ('Decor', 'Decor'), ('Linens', 'Linens')], default='Furniture', max_length=100)),
                ('image', models.ImageField(upload_to='')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
