# Generated by Django 4.2.6 on 2023-10-17 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('furniture_app', '0005_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_id',
            new_name='order_details',
        ),
    ]
