# Generated by Django 4.2.6 on 2023-10-17 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('furniture_app', '0006_rename_order_id_order_order_details'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
